# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updtime', models.CharField(max_length=100)),
                ('age_c', models.CharField(max_length=100)),
                ('age_e', models.CharField(max_length=100)),
                ('likecoun', models.CharField(max_length=100)),
                ('downcoun', models.CharField(max_length=100)),
                ('high_e', models.CharField(max_length=100)),
                ('audioname3', models.CharField(max_length=100)),
                ('audioname2', models.CharField(max_length=100)),
                ('audioname1', models.CharField(max_length=100)),
                ('qrimage1', models.CharField(max_length=100)),
                ('qrimage2', models.CharField(max_length=100)),
                ('mdesc', models.CharField(max_length=100)),
                ('rmid', models.CharField(max_length=100)),
                ('mid', models.CharField(max_length=100)),
                ('wide_e', models.CharField(max_length=100)),
                ('htmlpage', models.CharField(max_length=100)),
                ('addtime', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('wide_c', models.CharField(max_length=100)),
                ('mpath', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('high_c', models.CharField(max_length=100)),
                ('coldesc', models.CharField(max_length=100)),
                ('ext_1', models.CharField(max_length=100)),
                ('name_c', models.CharField(max_length=100)),
                ('name_e', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('material_c', models.CharField(max_length=100)),
                ('material_e', models.CharField(max_length=100)),
                ('intro_c', models.CharField(max_length=100)),
                ('intro_e', models.CharField(max_length=100)),
                ('colimage', models.CharField(max_length=100)),
                ('authoity', models.CharField(max_length=100)),
            ],
        ),
    ]
