# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellt', '0002_app_3dmodel_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_3dmodel_list',
            name='tname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
