# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellt', '0003_app_3dmodel_list_tname'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='bgImageName1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='bgImageName2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
