# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellt', '0004_auto_20170601_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_3DModel_list_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celImage', models.ImageField(upload_to='static')),
            ],
        ),
    ]
