# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerForX', '0002_auto_20170426_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraparameters',
            name='paraFile',
            field=models.FileField(upload_to=b'', verbose_name='./Cp/'),
        ),
    ]
